name: Go

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "go-api/**"

  push:
    branches: [ "main" ]
    paths:
      - "go-api/**"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: go-api

    strategy:
      matrix:
        go-version: ["1.24"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
